Update dx-clone-asset for python3 (#629)
This is to fix the error message below when running dx-toolkit in Python3:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/bin/dx-clone-asset", line 96, in _clone_asset_into_region
    project_id = _find_asset_project(region)
  File "/usr/local/bin/dx-clone-asset", line 79, in _find_asset_project
    projects = projects.split('\n')
TypeError: a bytes-like object is required, not 'str'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dx-clone-asset", line 208, in <module>
    main(args.record, args.regions, args.num_retries, args.priority)
  File "/usr/local/bin/dx-clone-asset", line 199, in main
    record_ids = clone_asset(record, regions, num_retries, priority)
  File "/usr/local/bin/dx-clone-asset", line 186, in clone_asset
    results = results.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: a bytes-like object is required, not 'str'
```